name: Periodic

on:
  workflow_dispatch:
#  schedule:
#    # Run weekly to check URL links still resolve
#    - cron: "0 8 * * WED"

# Note: linkcheck job removed - docs are now in smartem-devtools repo
# See https://github.com/DiamondLightSource/smartem-devtools for documentation
jobs: {}
